apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: provider-cosign-role
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs: ["list", "get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: provider-cosign-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: provider-cosign-role
subjects:
- kind: ServiceAccount
  name: provider-cosign-sa
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-cosign-sa
  namespace: default
